# Database local docker-compose (port 5452 from docker-compose.yaml)
spring.datasource.url=jdbc:postgresql://localhost:5452/flowable
spring.datasource.username=flowable
spring.datasource.password=flowable
spring.jpa.hibernate.ddl-auto=none
briany.security.allow-unauthenticated-engine-api=true

flowable.common.app.idm-admin.password=Local-Dev-Password-12345


# Logging verbose
logging.level.ru.briany=INFO
logging.level.ru.briany.observability.metric.ExternalWorkerMetricsInterceptor=INFO
logging.level.ru.briany.activity=DEBUG
logging.level.org.apache.kafka=INFO
logging.level.org.springframework.security=INFO
logging.level.org.springframework.kafka=INFO
logging.level.org.flowable=INFO
logging.level.org.springframework=INFO
logging.level.liquibase=DEBUG
logging.level.org.hibernate=WARN
logging.level.org.flowable.eventregistry=TRACE
logging.level.org.flowable.eventregistry.impl=TRACE
logging.level.org.flowable.eventregistry.kafka=TRACE
logging.level.org.flowable.engine=INFO
logging.level.org.flowable.engine.impl.event=DEBUG
logging.level.io.opentelemetry=WARN
logging.level.io.opentelemetry.sdk.trace=WARN
logging.level.io.grpc=WARN
logging.level.org.springframework.boot.autoconfigure=DEBUG

